// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo0VpFMppMNAPaHDI-6Iw9Tva0AUO2ImQ',
    appId: '1:38808997382:web:ac11aceeaf1cde45ff7d87',
    messagingSenderId: '38808997382',
    projectId: 'course-hotelio-a0470',
    authDomain: 'course-hotelio-a0470.firebaseapp.com',
    storageBucket: 'course-hotelio-a0470.appspot.com',
    measurementId: 'G-XM4XM7WREF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZfeLuIonqa3JUOBckEB5o8ChDP7_B_9Y',
    appId: '1:38808997382:android:e68ca5d115d34fc9ff7d87',
    messagingSenderId: '38808997382',
    projectId: 'course-hotelio-a0470',
    storageBucket: 'course-hotelio-a0470.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-MdfBdIKpfaxchX38hZfMKWDSO4sgU2s',
    appId: '1:38808997382:ios:76a93e5b1edcddffff7d87',
    messagingSenderId: '38808997382',
    projectId: 'course-hotelio-a0470',
    storageBucket: 'course-hotelio-a0470.appspot.com',
    iosBundleId: 'com.rangga.hotelio',
  );
}
